# Generated by Django 5.0.3 on 2024-03-27 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('unitNumber', models.IntegerField()),
                ('civicNumber', models.IntegerField()),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=2)),
                ('postalCode', models.CharField(max_length=3)),
                ('createdAt', models.DateTimeField(verbose_name=datetime.datetime(2024, 3, 27, 16, 48, 2, 4694, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
