# Generated by Django 5.0.3 on 2024-03-30 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 30, 16, 44, 51, 854196)),
        ),
    ]
