# Generated by Django 5.0.3 on 2024-04-18 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contact_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 18, 9, 18, 47, 242740)),
        ),
    ]
