"""
Django settings for contactApp project.

Generated by 'django-admin startproject' using Django 5.0.3.

"""

from pathlib import Path
import dj_database_url
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


SECRET_KEY = 'django-insecure-yyb4^esqc!zv=#thm=crp1%e0e65y5=x)2t-2$-k-%)58c8e#m'

DEBUG = False

ALLOWED_HOSTS = ['localhost', '.vercel.app']


SESSION_EXPIRE_SECONDS = 1800
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_EXPIRE_AFTER_LAST_ACTIVITY_GRACE_PERIOD = 60
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contacts',
    'users'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'contactApp.middleware.handleServerErrors.ExceptionMiddleware'
]

ROOT_URLCONF = 'contactApp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'contactApp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


databaseUrl = os.environ.get('DATABASE_URL')
if os.environ.get('APP_ENV') == 'production':
    DATABASES['default'] = dj_database_url.parse(databaseUrl)


if os.environ.get('HOST_SITE') == 'vercel':
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'railway',
        'USER':'postgres',
        'PASSWORD':'HRuRLiiiyzrTDefFFOTeCvsACaEbiFhQ',
        'HOST': 'roundhouse.proxy.rlwy.net',
        'PORT': '38455'
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/New_York'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        }
    },
    'formatters': {
        'verbose': {
            'format': '[contactor] %(levelname)s %(asctime)s %(message)s'
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG'
        },
       'sysFile': {
           'level': 'DEBUG',
           'class': 'logging.FileHandler',
           'filename': 'logs/system.log',
           'formatter': 'verbose',
           'filters': ['require_debug_false'],

       },
       'errorFile': {
           'level': 'ERROR',
           'class': 'logging.FileHandler',
           'filename': 'logs/error.log',
           'formatter': 'verbose',
           'filters': ['require_debug_false'],

       },
       'warningFile': {
           'level': 'WARNING',
           'class': 'logging.FileHandler',
           'filename': 'logs/error.log',
           'formatter': 'verbose',
           'filters': ['require_debug_false'],

       },
    },
    'loggers': {
        'django': {
            'handlers': ['console','sysFile','errorFile','warningFile'],
            'propagate': False
        },
        
    },
    "root": {
        "handlers": ["errorFile", 'warningFile']
    },
}
